export const GET_ALL_BRANDS = 'GET_ALL_BRANDS'
export const GET_BRAND = 'GET_BRAND'
export const LOAD_BRAND = 'LOAD_BRAND'
export const ERROR_BRAND = 'ERROR_BRAND'
export const ADD_BRAND = 'ADD_BRAND'
export const UPDATE_BRAND = 'UPDATE_BRAND'
export const DELETE_BRAND = 'DELETE_BRAND'
